server:
  port: 80

# 图片存储地址
web:
  upd-path: F:/WorkStation/Java/Fooprd-upd/
  dwd-path: F:/WorkStation/Java/Fooprd-dwd/

# datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/fooprd?useSSL=true
    username: root
    password: root


