server:
  port: 80

# 图片存储地址
web:
  upd-path: F:/WorkStation/Java/Foo-upd/

spring:
# 表示所有的访问都经过静态资源路径；
  mvc:
    static-path-pattern: /**
# 加入所有静态资源路径（覆盖默认配置）
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upd-path}

#  文件上传大小限制
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 500Mb

# thymeleaf
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    mode: HTML
    encoding: utf-8
    content-type: text/html

# datasource
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/home?useSSL=true
    username: root
    password: root

# pagehelper(https://github.com/pagehelper/Mybatis-PageHelper/blob/master/wikis/zh/HowToUse.md)
  pagehelper:
    offset-as-page-num: true
    helper-dialect: mysql
    row-bounds-with-count: true
    reasonable: true

