server:
  port: 8080

# 图片存储地址
web:
  upd-path: F:/WorkStation/Java/Foodev-upd/
  dwd-path: F:/WorkStation/Java/Foodev-dwd/

# datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/foodev?useSSL=true
    username: root
    password: root


